# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fillinmar/semc++/techno-ih2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fillinmar/semc++/techno-ih2/build

# Include any dependencies generated for this target.
include src/parallel_matrix/CMakeFiles/parallel_matrix.dir/depend.make

# Include the progress variables for this target.
include src/parallel_matrix/CMakeFiles/parallel_matrix.dir/progress.make

# Include the compile flags for this target's objects.
include src/parallel_matrix/CMakeFiles/parallel_matrix.dir/flags.make

src/parallel_matrix/CMakeFiles/parallel_matrix.dir/matrix.c.o: src/parallel_matrix/CMakeFiles/parallel_matrix.dir/flags.make
src/parallel_matrix/CMakeFiles/parallel_matrix.dir/matrix.c.o: ../src/parallel_matrix/matrix.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/fillinmar/semc++/techno-ih2/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object src/parallel_matrix/CMakeFiles/parallel_matrix.dir/matrix.c.o"
	cd /home/fillinmar/semc++/techno-ih2/build/src/parallel_matrix && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/parallel_matrix.dir/matrix.c.o   -c /home/fillinmar/semc++/techno-ih2/src/parallel_matrix/matrix.c

src/parallel_matrix/CMakeFiles/parallel_matrix.dir/matrix.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/parallel_matrix.dir/matrix.c.i"
	cd /home/fillinmar/semc++/techno-ih2/build/src/parallel_matrix && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/fillinmar/semc++/techno-ih2/src/parallel_matrix/matrix.c > CMakeFiles/parallel_matrix.dir/matrix.c.i

src/parallel_matrix/CMakeFiles/parallel_matrix.dir/matrix.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/parallel_matrix.dir/matrix.c.s"
	cd /home/fillinmar/semc++/techno-ih2/build/src/parallel_matrix && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/fillinmar/semc++/techno-ih2/src/parallel_matrix/matrix.c -o CMakeFiles/parallel_matrix.dir/matrix.c.s

# Object files for target parallel_matrix
parallel_matrix_OBJECTS = \
"CMakeFiles/parallel_matrix.dir/matrix.c.o"

# External object files for target parallel_matrix
parallel_matrix_EXTERNAL_OBJECTS =

src/parallel_matrix/libparallel_matrix.so: src/parallel_matrix/CMakeFiles/parallel_matrix.dir/matrix.c.o
src/parallel_matrix/libparallel_matrix.so: src/parallel_matrix/CMakeFiles/parallel_matrix.dir/build.make
src/parallel_matrix/libparallel_matrix.so: src/parallel_matrix/CMakeFiles/parallel_matrix.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/fillinmar/semc++/techno-ih2/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking C shared library libparallel_matrix.so"
	cd /home/fillinmar/semc++/techno-ih2/build/src/parallel_matrix && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/parallel_matrix.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/parallel_matrix/CMakeFiles/parallel_matrix.dir/build: src/parallel_matrix/libparallel_matrix.so

.PHONY : src/parallel_matrix/CMakeFiles/parallel_matrix.dir/build

src/parallel_matrix/CMakeFiles/parallel_matrix.dir/clean:
	cd /home/fillinmar/semc++/techno-ih2/build/src/parallel_matrix && $(CMAKE_COMMAND) -P CMakeFiles/parallel_matrix.dir/cmake_clean.cmake
.PHONY : src/parallel_matrix/CMakeFiles/parallel_matrix.dir/clean

src/parallel_matrix/CMakeFiles/parallel_matrix.dir/depend:
	cd /home/fillinmar/semc++/techno-ih2/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/fillinmar/semc++/techno-ih2 /home/fillinmar/semc++/techno-ih2/src/parallel_matrix /home/fillinmar/semc++/techno-ih2/build /home/fillinmar/semc++/techno-ih2/build/src/parallel_matrix /home/fillinmar/semc++/techno-ih2/build/src/parallel_matrix/CMakeFiles/parallel_matrix.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/parallel_matrix/CMakeFiles/parallel_matrix.dir/depend

