# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# compile C with /usr/bin/cc
C_FLAGS = --coverage -fPIC   -std=gnu99

C_DEFINES = -Dparallel_matrix_EXPORTS

C_INCLUDES = -I/home/fillinmar/semc++/techno-ih2/src/parallel_matrix 

